### ISSUE TITLE
I believe this may be bullying certain Employees

### ISSUE THREAD

**Issue by drinkataco** [Bluetel-Solutions/what-would-rob-say#1]

**Comment by alexwilson** [comment]
DENIED

**Comment by memphisx** [comment]
WTF????

_Kyriakos Bompotis_

_E:_ kb@bluetel.co.uk
_S:_ bluetel.solutions

Bluetel Solutions Limited
Registered office: The Walker Building, 58 Oxford Street, Birmingham, B5 5NR
Registered in England #05364409

This e-mail is confidential and may contain legally privileged information.
If you are not its intended recipient, you may not copy, forward, disclose
or use any part of it. If you have received it in error, please delete it
and all copies from your system.

**Comment by alexwilson** [comment]
What?
